In [1]:
import requests
import numpy
import pandas

# Coleta de dados

In [2]:
url = "https://www.fundsexplorer.com.br/ranking"
headers = {
    'User-Agent':
        'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0'
}

In [3]:
response = requests.get(url=url, headers=headers)
if response.status_code == 200:
    data_frame = pandas.read_html(response.content, encoding='utf-8')[0]

# Tratamento de Dados

In [4]:
data_frame.sort_values('Códigodo fundo', inplace=True)

In [5]:
data_frame['Setor'].unique()

array(['Shoppings', 'Títulos e Val. Mob.', 'Lajes Corporativas',
       'Logística', 'Híbrido', 'Outros', nan, 'Hospital', 'Residencial',
       'Hotel'], dtype=object)

In [6]:
data_frame.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

In [7]:
data_frame

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
229,ABCP11,Shoppings,"R$ 71,12",1019.0,"R$ 0,54","0,77%","2,47%","4,77%","9,08%","0,82%",...,"R$ 1.120.247.855,81","R$ 91,79",77.0,"0,64%","-0,04%","0,61%","3,33%","7,50%",NaN,1
98,AFHI11,Títulos e Val. Mob.,"R$ 99,25",3069.0,"R$ 1,40","1,37%","4,03%","7,86%","14,40%","1,34%",...,"R$ 173.824.946,40","R$ 97,24",102.0,"1,39%","0,44%","1,83%","3,20%",NaN,NaN,0
105,AFOF11,Títulos e Val. Mob.,"R$ 88,99",500.0,"R$ 1,08","1,19%","3,53%","6,65%","0,00%","1,18%",...,"R$ 69.242.339,50","R$ 100,18",89.0,"1,08%","-2,09%","-1,04%","4,47%",NaN,NaN,0
257,AIEC11,Lajes Corporativas,"R$ 73,84",3885.0,"R$ 0,80","1,05%","2,84%","6,07%","10,82%","0,95%",...,"R$ 489.073.625,01","R$ 101,36",73.0,"0,71%","0,12%","0,83%","3,49%","0,00%",NaN,2
3,ALMI11,Lajes Corporativas,"R$ 899,49",2.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 249.632.973,43","R$ 2.245,37",40.0,NaN,NaN,NaN,NaN,"64,05%",NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,XPML11,Shoppings,"R$ 92,32",34352.0,"R$ 0,68","0,70%","2,06%","4,30%","7,63%","0,69%",...,"R$ 1.892.808.419,44","R$ 101,32",91.0,"0,67%","0,01%","0,68%","1,93%","3,90%",NaN,16
132,XPPR11,Outros,"R$ 45,15",28157.0,"R$ 0,35","0,70%","2,30%","4,56%","9,56%","0,77%",...,"R$ 565.410.376,25","R$ 77,28",58.0,"0,58%","-1,54%","-0,96%","-2,87%","46,00%","0,00%",4
201,XPSF11,Outros,"R$ 6,93",69269.0,"R$ 0,07","0,99%","2,87%","5,56%","10,70%","0,96%",...,"R$ 375.228.449,53","R$ 8,67",80.0,"0,80%","-90,09%","-90,02%","-89,78%",NaN,NaN,0
2,XTED11,Lajes Corporativas,"R$ 6,01",649.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 27.305.951,24","R$ 13,89",43.0,NaN,NaN,NaN,NaN,"0,00%","100,00%",1
38,YUFI11B,Residencial,NaN,NaN,"R$ 0,60","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 41.106.356,80","R$ 104,03",NaN,"0,58%","-0,28%","0,29%","2,72%",NaN,NaN,0

In [8]:
data_frame[data_frame['Setor'].isna()]

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
281,BIME11,NaN,"R$ 9,51",13554.0,"R$ 0,16","1,68%","4,67%","8,17%","0,00%","1,56%",...,"R$ 55.313.386,31","R$ 9,46",101.0,"1,59%","-0,49%","1,09%","4,17%",NaN,NaN,0
269,CXCI11,NaN,"R$ 76,81",2005.0,"R$ 0,80","1,04%","0,00%","0,00%","0,00%","0,00%",...,"R$ 200.991.074,86","R$ 97,68",79.0,"0,72%","-0,07%","0,65%","0,96%",NaN,NaN,0
68,ERPA11,NaN,"R$ 120,00",1000.0,"R$ 0,28","0,22%","0,00%","0,00%","0,00%","0,00%",...,"R$ 57.806.170,89","R$ 115,40",104.0,"0,20%","0,24%","0,43%","0,43%",NaN,NaN,0
59,GTLG11,NaN,"R$ 99,83",1393.0,"R$ 0,70","0,70%","2,10%","4,21%","0,00%","0,70%",...,"R$ 675.663.743,88","R$ 94,20",106.0,"0,74%","-1,52%","-0,79%","-0,28%",NaN,NaN,0

# Definindo tipo de Dados Categóricos e Numéricos

In [9]:
categorical_columns = ['Códigodo fundo', 'Setor']
data_frame[categorical_columns] = data_frame[categorical_columns].astype('category')

In [10]:
float_columns = list(data_frame.iloc[:, 2:-1].columns)
data_frame[float_columns] = data_frame[float_columns].fillna(value=0)
data_frame[float_columns] = data_frame[float_columns].applymap(lambda x: str(x).replace('R$','').replace('.','').replace('%','').replace(',', '.'))
data_frame[float_columns] = data_frame[float_columns].astype('float')

In [11]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 282 entries, 229 to 38
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           282 non-null    category
 1   Setor                    278 non-null    category
 2   Preço Atual              282 non-null    float64
 3   Liquidez Diária          282 non-null    float64
 4   Dividendo                282 non-null    float64
 5   DividendYield            282 non-null    float64
 6   DY (3M)Acumulado         282 non-null    float64
 7   DY (6M)Acumulado         282 non-null    float64
 8   DY (12M)Acumulado        282 non-null    float64
 9   DY (3M)Média             282 non-null    float64
 10  DY (6M)Média             282 non-null    float64
 11  DY (12M)Média            282 non-null    float64
 12  DY Ano                   282 non-null    float64
 13  Variação Preço           282 non-null    float64
 14  Rentab.Período           282 non-null    float64
 15  Rentab.Acumulada         282 non-null    float64
 16  PatrimônioLíq.           282 non-null    float64
 17  VPA                      282 non-null    float64
 18  P/VPA                    282 non-null    float64
 19  DYPatrimonial            282 non-null    float64
 20  VariaçãoPatrimonial      282 non-null    float64
 21  Rentab. Patr.no Período  282 non-null    float64
 22  Rentab. Patr.Acumulada   282 non-null    float64
 23  VacânciaFísica           282 non-null    float64
 24  VacânciaFinanceira       282 non-null    float64
 25  QuantidadeAtivos         282 non-null    int64
dtypes: category(2), float64(23), int64(1)
memory usage: 66.6 KB

# Realizando ajustes finais no dataframe

In [12]:
# checking infinity values
data_frame[numpy.isinf(data_frame[float_columns]).any(1)]

Empty DataFrame
Columns: [Códigodo fundo, Setor, Preço Atual, Liquidez Diária, Dividendo, DividendYield, DY (3M)Acumulado, DY (6M)Acumulado, DY (12M)Acumulado, DY (3M)Média, DY (6M)Média, DY (12M)Média, DY Ano, Variação Preço, Rentab.Período, Rentab.Acumulada, PatrimônioLíq., VPA, P/VPA, DYPatrimonial, VariaçãoPatrimonial, Rentab. Patr.no Período, Rentab. Patr.Acumulada, VacânciaFísica, VacânciaFinanceira, QuantidadeAtivos]
Index: []

[0 rows x 26 columns]

In [13]:
# adjusting columns
data_frame['Liquidez Diária'] = data_frame['Liquidez Diária']/10
data_frame['P/VPA'] = data_frame['P/VPA']/1000

In [14]:
data_frame

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
229,ABCP11,Shoppings,71.12,1019.0,0.54,0.77,2.47,4.77,9.08,0.82,...,1.120248e+09,91.79,0.77,0.64,-0.04,0.61,3.33,7.50,0.0,1
98,AFHI11,Títulos e Val. Mob.,99.25,3069.0,1.40,1.37,4.03,7.86,14.40,1.34,...,1.738249e+08,97.24,1.02,1.39,0.44,1.83,3.20,0.00,0.0,0
105,AFOF11,Títulos e Val. Mob.,88.99,500.0,1.08,1.19,3.53,6.65,0.00,1.18,...,6.924234e+07,100.18,0.89,1.08,-2.09,-1.04,4.47,0.00,0.0,0
257,AIEC11,Lajes Corporativas,73.84,3885.0,0.80,1.05,2.84,6.07,10.82,0.95,...,4.890736e+08,101.36,0.73,0.71,0.12,0.83,3.49,0.00,0.0,2
3,ALMI11,Lajes Corporativas,899.49,2.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.496330e+08,2245.37,0.40,0.00,0.00,0.00,0.00,64.05,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,XPML11,Shoppings,92.32,34352.0,0.68,0.70,2.06,4.30,7.63,0.69,...,1.892808e+09,101.32,0.91,0.67,0.01,0.68,1.93,3.90,0.0,16
132,XPPR11,Outros,45.15,28157.0,0.35,0.70,2.30,4.56,9.56,0.77,...,5.654104e+08,77.28,0.58,0.58,-1.54,-0.96,-2.87,46.00,0.0,4
201,XPSF11,Outros,6.93,69269.0,0.07,0.99,2.87,5.56,10.70,0.96,...,3.752284e+08,8.67,0.80,0.80,-90.09,-90.02,-89.78,0.00,0.0,0
2,XTED11,Lajes Corporativas,6.01,649.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.730595e+07,13.89,0.43,0.00,0.00,0.00,0.00,0.00,100.0,1
38,YUFI11B,Residencial,0.00,0.0,0.60,0.00,0.00,0.00,0.00,0.00,...,4.110636e+07,104.03,0.00,0.58,-0.28,0.29,2.72,0.00,0.0,0

In [15]:
data_frame.describe()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000,...,2.820000e+02,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000,282.000000
mean,475.047163,14489.039007,1.236667,0.900071,2.538794,4.684149,7.736348,0.846525,0.780603,0.644823,...,5.235795e+08,516.924929,0.844823,0.745851,-0.769149,-0.029184,1.097340,6.513582,1.186915,3.092199
std,4751.705234,42384.212674,2.517016,0.482717,1.339801,2.552260,5.090615,0.446784,0.425257,0.424185,...,7.816488e+08,4544.557625,0.674381,0.478636,7.758428,7.833902,11.691103,16.657419,7.502954,7.686843
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.025113e+07,-13.520000,-0.470000,0.000000,-90.090000,-90.020000,-98.910000,0.000000,0.000000,0.000000
25%,62.065000,174.750000,0.462500,0.672500,1.920000,3.530000,3.662500,0.642500,0.592500,0.305000,...,1.015943e+08,87.502500,0.702500,0.490000,-0.415000,0.000000,0.412500,0.000000,0.000000,0.000000
50%,86.660000,1503.000000,0.750000,0.920000,2.565000,4.940000,8.760000,0.855000,0.820000,0.730000,...,2.375445e+08,98.085000,0.850000,0.710000,0.000000,0.520000,2.220000,0.000000,0.000000,0.000000
75%,99.952500,11474.250000,1.250000,1.220000,3.462500,6.537500,11.160000,1.157500,1.090000,0.930000,...,5.824695e+08,108.707500,0.980000,1.110000,0.067500,1.040000,4.155000,2.550000,0.000000,3.000000
max,76000.000000,447468.000000,26.660000,2.900000,7.330000,9.890000,18.350000,2.440000,1.650000,1.530000,...,6.938900e+09,70498.040000,11.230000,1.930000,19.220000,20.560000,29.920000,100.000000,100.000000,72.000000

In [36]:
indicadores = [
    'Códigodo fundo',
    'Setor',
    'DY (12M)Acumulado',
    'VacânciaFísica',
    'P/VPA',
    'QuantidadeAtivos',
    'Liquidez Diária',
    'PatrimônioLíq.',
]

In [37]:
df_aux = data_frame[indicadores]

In [38]:
df_aux

,Códigodo fundo,Setor,DY (12M)Acumulado,VacânciaFísica,P/VPA,QuantidadeAtivos,Liquidez Diária,PatrimônioLíq.
229,ABCP11,Shoppings,9.08,7.50,0.77,1,1019.0,1.120248e+09
98,AFHI11,Títulos e Val. Mob.,14.40,0.00,1.02,0,3069.0,1.738249e+08
105,AFOF11,Títulos e Val. Mob.,0.00,0.00,0.89,0,500.0,6.924234e+07
257,AIEC11,Lajes Corporativas,10.82,0.00,0.73,2,3885.0,4.890736e+08
3,ALMI11,Lajes Corporativas,0.00,64.05,0.40,1,2.0,2.496330e+08
...,...,...,...,...,...,...,...,...
111,XPML11,Shoppings,7.63,3.90,0.91,16,34352.0,1.892808e+09
132,XPPR11,Outros,9.56,46.00,0.58,4,28157.0,5.654104e+08
201,XPSF11,Outros,10.70,0.00,0.80,0,69269.0,3.752284e+08
2,XTED11,Lajes Corporativas,0.00,0.00,0.43,1,649.0,2.730595e+07
38,YUFI11B,Residencial,0.00,0.00,0.00,0,0.0,4.110636e+07

In [39]:
media_setor = df_aux.groupby('Setor').agg(['mean', 'std'])

/tmp/ipykernel_136/1208675878.py:1: FutureWarning: ['Códigodo fundo'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  media_setor = df_aux.groupby('Setor').agg(['mean', 'std'])

In [40]:
media_setor

                    DY (12M)Acumulado           VacânciaFísica             \
                                 mean       std           mean        std
Setor
Hospital                     8.563333  1.468650       0.000000   0.000000
Hotel                        6.796667  3.120342      43.300000  37.498933
Híbrido                      7.044583  5.058959       2.220833   5.098410
Lajes Corporativas           6.769512  4.408152      26.366341  29.492080
Logística                    8.149091  2.869481       7.263636  17.558000
Outros                       8.881351  5.123415       2.469459   8.223041
Residencial                  1.738000  3.705305       3.040000   8.802424
Shoppings                    5.830909  2.919007      10.806364  12.131324
Títulos e Val. Mob.          9.416630  5.547531       0.000000   0.000000

                        P/VPA           QuantidadeAtivos             \
                         mean       std             mean        std
Setor
Hospital             0.763333  0.076376         1.000000   0.000000
Hotel                0.830000  0.251595         9.333333  12.096832
Híbrido              0.767292  0.318452         3.687500   6.088553
Lajes Corporativas   0.698049  0.273013         4.097561  10.270844
Logística            0.831364  0.131014         7.409091   5.586200
Outros               0.771081  0.257766         6.027027  14.078128
Residencial          0.688000  0.614343         0.600000   1.349897
Shoppings            0.690455  0.218773         4.454545   5.369466
Títulos e Val. Mob.  1.035000  1.085093         0.065217   0.625543

                    Liquidez Diária               PatrimônioLíq.
                               mean           std           mean           std
Setor
Hospital                1197.666667    873.595635   2.724733e+08  2.397485e+08
Hotel                    568.000000    733.173240   2.164871e+08  1.234496e+08
Híbrido                15554.062500  64380.799817   5.130913e+08  8.047853e+08
Lajes Corporativas      3496.731707   6918.265364   3.667970e+08  4.119942e+08
Logística              11087.590909  16387.579012   9.082502e+08  9.560734e+08
Outros                 13222.378378  21724.434301   4.531304e+08  5.196859e+08
Residencial              545.600000   1027.719179   1.316364e+08  1.298815e+08
Shoppings               4833.681818   9098.529035   6.745854e+08  6.712265e+08
Títulos e Val. Mob.    25301.597826  53656.913160   5.719689e+08  9.835774e+08

In [41]:
media_setor.loc['Hospital']

DY (12M)Acumulado  mean    8.563333e+00
                   std     1.468650e+00
VacânciaFísica     mean    0.000000e+00
                   std     0.000000e+00
P/VPA              mean    7.633333e-01
                   std     7.637626e-02
QuantidadeAtivos   mean    1.000000e+00
                   std     0.000000e+00
Liquidez Diária    mean    1.197667e+03
                   std     8.735956e+02
PatrimônioLíq.     mean    2.724733e+08
                   std     2.397485e+08
Name: Hospital, dtype: float64

In [63]:
def oportunidade_media_setor(dataframe, setor='Shoppings', label_setor='Setor'):
    media_setor = df_aux.groupby('Setor').agg(['mean', 'std'])
    
    df_setor = dataframe[dataframe[label_setor].isin([setor])]
    
    filter = \
            (df_setor['QuantidadeAtivos'] > 0) & \
            (df_setor['Liquidez Diária'] > 4000) & \
            (df_setor['P/VPA'] < 1.0) & \
            (df_setor['DY (12M)Acumulado'] > media_setor.loc[setor, ('DY (12M)Acumulado', 'mean')])
            
    print('Média do setor Yield: {}'.format(media_setor.loc[setor, ('DY (12M)Acumulado', 'mean')]))
    print('Média do setor P/VPA: {}'.format(media_setor.loc[setor, ('P/VPA', 'mean')]))
    print('Média do setor Ativos: {}'.format(media_setor.loc[setor, ('QuantidadeAtivos', 'mean')]))
    
    return df_setor[filter]

In [64]:
oportunidade = oportunidade_media_setor(df_aux, setor='Shoppings')
oportunidade.sort_values('DY (12M)Acumulado', ascending=False, inplace=True)
# oportunidade['PatrimônioLíq.'] *= 10
oportunidade['PatrimônioLíq.'].apply(lambda x: '%.1f' % x).values.tolist()
oportunidade

Média do setor Yield: 5.830909090909091
Média do setor P/VPA: 0.6904545454545454
Média do setor Ativos: 4.454545454545454

/tmp/ipykernel_136/3930435299.py:2: FutureWarning: ['Códigodo fundo'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  media_setor = df_aux.groupby('Setor').agg(['mean', 'std'])

,Códigodo fundo,Setor,DY (12M)Acumulado,VacânciaFísica,P/VPA,QuantidadeAtivos,Liquidez Diária,PatrimônioLíq.
236,HSML11,Shoppings,8.49,4.5,0.81,5,22801.0,1.470238e+09
199,MALL11,Shoppings,8.10,4.0,0.92,8,10732.0,8.191508e+08
153,VISC11,Shoppings,7.71,8.3,0.86,15,19031.0,2.037764e+09
111,XPML11,Shoppings,7.63,3.9,0.91,16,34352.0,1.892808e+09
244,HGBS11,Shoppings,7.12,6.5,0.80,17,6178.0,2.165192e+09