In [1]:
import requests
import numpy
import pandas

# Coleta de dados

In [2]:
url = "https://www.fundsexplorer.com.br/ranking"
headers = {
    'User-Agent':
        'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0'
}

In [3]:
response = requests.get(url=url, headers=headers)
if response.status_code == 200:
    data_frame = pandas.read_html(response.content, encoding='utf-8')[0]

# Tratamento de Dados

In [4]:
data_frame.sort_values('Códigodo fundo', inplace=True)

In [5]:
data_frame.describe(include='all')

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,277,274,268,268.000000,277,271,271,271,271,271,...,277,277,268.000000,239,239,239,239,123,30,277.000000
unique,277,9,252,NaN,120,104,177,182,178,105,...,277,271,NaN,104,111,145,160,73,18,NaN
top,ABCP11,Títulos e Val. Mob.,"R$ 100,00",NaN,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 1.120.197.062,39","R$ 97,23",NaN,"0,59%","0,00%","0,52%","0,78%","0,00%","0,00%",NaN
freq,1,89,3,NaN,14,22,32,48,71,32,...,1,2,NaN,7,74,6,6,42,13,NaN
mean,NaN,NaN,NaN,16411.436567,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,87.350746,NaN,NaN,NaN,NaN,NaN,NaN,3.148014
std,NaN,NaN,NaN,46325.256464,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,47.458440,NaN,NaN,NaN,NaN,NaN,NaN,7.744781
min,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-71.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,205.250000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,75.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,2708.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,88.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,NaN,NaN,NaN,13326.750000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,99.250000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
max,NaN,NaN,NaN,524297.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,760.000000,NaN,NaN,NaN,NaN,NaN,NaN,72.000000

In [6]:
data_frame['Setor'].unique()

array(['Shoppings', 'Títulos e Val. Mob.', 'Lajes Corporativas',
       'Logística', 'Híbrido', 'Outros', nan, 'Hospital', 'Residencial',
       'Hotel'], dtype=object)

In [7]:
data_frame.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

In [8]:
data_frame.isna().sum()

Códigodo fundo               0
Setor                        3
Preço Atual                  9
Liquidez Diária              9
Dividendo                    0
DividendYield                6
DY (3M)Acumulado             6
DY (6M)Acumulado             6
DY (12M)Acumulado            6
DY (3M)Média                 6
DY (6M)Média                 6
DY (12M)Média                6
DY Ano                      19
Variação Preço               6
Rentab.Período               6
Rentab.Acumulada             6
PatrimônioLíq.               0
VPA                          0
P/VPA                        9
DYPatrimonial               38
VariaçãoPatrimonial         38
Rentab. Patr.no Período     38
Rentab. Patr.Acumulada      38
VacânciaFísica             154
VacânciaFinanceira         247
QuantidadeAtivos             0
dtype: int64

# Dados Categóricos

In [9]:
data_frame[data_frame['Setor'].isna()]

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
164,BIME11,NaN,"R$ 9,16",11689.0,"R$ 0,11","1,16%","3,25%","0,00%","0,00%","1,08%",...,"R$ 55.631.464,69","R$ 9,52",96.0,"1,16%","-1,79%","-0,65%","0,37%",NaN,NaN,0
105,CYCR11,NaN,"R$ 99,79",37.0,"R$ 1,15","1,15%","0,00%","0,00%","0,00%","0,00%",...,"R$ 60.293.805,33","R$ 94,34",106.0,"1,22%","0,00%","1,22%","1,22%",NaN,NaN,0
202,GTLG11,NaN,"R$ 99,98",2.0,"R$ 0,70","0,70%","2,11%","0,00%","0,00%","0,70%",...,"R$ 699.410.585,54","R$ 97,51",103.0,"0,72%","-0,44%","0,27%","0,99%",NaN,NaN,0

In [10]:
categorical_columns = ['Códigodo fundo', 'Setor']

In [11]:
data_frame[categorical_columns] = data_frame[categorical_columns].astype('category')

In [12]:
data_frame

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
109,ABCP11,Shoppings,"R$ 74,67",1840.0,"R$ 0,45","0,58%","2,45%","4,66%","7,28%","0,82%",...,"R$ 1.120.197.062,39","R$ 91,79",81.0,"0,49%","0,06%","0,55%","1,39%","7,50%",NaN,1
245,AFHI11,Títulos e Val. Mob.,"R$ 99,90",7148.0,"R$ 1,30","1,27%","3,83%","7,43%","0,00%","1,28%",...,"R$ 173.063.751,55","R$ 96,81",103.0,"1,34%","0,00%","1,34%","1,34%",NaN,NaN,0
251,AFOF11,Títulos e Val. Mob.,"R$ 94,00",1005.0,"R$ 1,00","1,07%","3,11%","6,25%","0,00%","1,04%",...,"R$ 69.843.469,38","R$ 101,05",93.0,"0,99%","1,26%","2,26%","3,24%",NaN,NaN,0
149,AIEC11,Lajes Corporativas,"R$ 83,49",1752.0,"R$ 0,68","0,88%","2,49%","4,95%","9,01%","0,83%",...,"R$ 491.831.341,80","R$ 101,93",82.0,"0,67%","0,03%","0,69%","1,30%","0,00%",NaN,2
3,ALMI11,Lajes Corporativas,"R$ 890,00",15.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 250.487.663,18","R$ 2.253,05",40.0,NaN,NaN,NaN,NaN,"64,05%",NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,XPML11,Shoppings,"R$ 94,64",41437.0,"R$ 0,64","0,71%","2,24%","3,93%","6,37%","0,75%",...,"R$ 1.900.952.211,41","R$ 101,76",93.0,"0,59%","0,00%","0,59%","0,59%","3,90%",NaN,16
103,XPPR11,Outros,"R$ 56,31",19125.0,"R$ 0,45","0,77%","2,28%","4,90%","9,36%","0,76%",...,"R$ 577.562.461,09","R$ 78,94",71.0,"0,57%","-3,56%","-3,01%","-2,48%","46,00%","0,00%",4
141,XPSF11,Outros,"R$ 70,01",19743.0,"R$ 0,66","0,91%","2,58%","5,30%","10,12%","0,86%",...,"R$ 370.250.982,09","R$ 85,50",82.0,"0,77%","-2,97%","-2,22%","-1,50%",NaN,NaN,0
2,XTED11,Lajes Corporativas,"R$ 6,20",337.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 27.391.929,40","R$ 13,94",44.0,NaN,NaN,NaN,NaN,"0,00%","100,00%",1
64,YUFI11B,Residencial,NaN,NaN,"R$ 0,84","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 41.354.358,01","R$ 104,65",NaN,"0,80%","0,20%","1,00%","1,52%",NaN,NaN,0

In [13]:
float_columns = list(data_frame.iloc[:, 2:-1].columns)

In [15]:
float_columns = list(data_frame.iloc[:, 2:-1].columns)
data_frame[float_columns] = data_frame[float_columns].fillna(value=0)
data_frame[float_columns] = data_frame[float_columns].applymap(lambda x: str(x).replace('R$','').replace('.','').replace('%','').replace(',', '.'))
data_frame[float_columns] = data_frame[float_columns].astype('float')

In [16]:
data_frame[float_columns] = data_frame[float_columns].applymap(lambda x: str(x).replace('R$','').replace('.','').replace('%','').replace(',', '.'))

In [17]:
data_frame[float_columns] = data_frame[float_columns].astype('float')

In [18]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 277 entries, 109 to 64
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           277 non-null    category
 1   Setor                    274 non-null    category
 2   Preço Atual              277 non-null    float64
 3   Liquidez Diária          277 non-null    float64
 4   Dividendo                277 non-null    float64
 5   DividendYield            277 non-null    float64
 6   DY (3M)Acumulado         277 non-null    float64
 7   DY (6M)Acumulado         277 non-null    float64
 8   DY (12M)Acumulado        277 non-null    float64
 9   DY (3M)Média             277 non-null    float64
 10  DY (6M)Média             277 non-null    float64
 11  DY (12M)Média            277 non-null    float64
 12  DY Ano                   277 non-null    float64
 13  Variação Preço           277 non-null    float64
 14  Rentab.Período           277 non-null    float64
 15  Rentab.Acumulada         277 non-null    float64
 16  PatrimônioLíq.           277 non-null    float64
 17  VPA                      277 non-null    float64
 18  P/VPA                    277 non-null    float64
 19  DYPatrimonial            277 non-null    float64
 20  VariaçãoPatrimonial      277 non-null    float64
 21  Rentab. Patr.no Período  277 non-null    float64
 22  Rentab. Patr.Acumulada   277 non-null    float64
 23  VacânciaFísica           277 non-null    float64
 24  VacânciaFinanceira       277 non-null    float64
 25  QuantidadeAtivos         277 non-null    int64
dtypes: category(2), float64(23), int64(1)
memory usage: 65.5 KB

In [19]:
# checking infinity values
data_frame[numpy.isinf(data_frame[float_columns]).any(1)]

Empty DataFrame
Columns: [Códigodo fundo, Setor, Preço Atual, Liquidez Diária, Dividendo, DividendYield, DY (3M)Acumulado, DY (6M)Acumulado, DY (12M)Acumulado, DY (3M)Média, DY (6M)Média, DY (12M)Média, DY Ano, Variação Preço, Rentab.Período, Rentab.Acumulada, PatrimônioLíq., VPA, P/VPA, DYPatrimonial, VariaçãoPatrimonial, Rentab. Patr.no Período, Rentab. Patr.Acumulada, VacânciaFísica, VacânciaFinanceira, QuantidadeAtivos]
Index: []

[0 rows x 26 columns]

In [20]:
# adjusting columns
data_frame['Liquidez Diária'] = data_frame['Liquidez Diária']/10
data_frame['P/VPA'] = data_frame['P/VPA']/1000

In [21]:
data_frame

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
109,ABCP11,Shoppings,74.67,1840.0,0.45,0.58,2.45,4.66,7.28,0.82,...,1.120197e+09,91.79,0.81,0.49,0.06,0.55,1.39,7.50,0.0,1
245,AFHI11,Títulos e Val. Mob.,99.90,7148.0,1.30,1.27,3.83,7.43,0.00,1.28,...,1.730638e+08,96.81,1.03,1.34,0.00,1.34,1.34,0.00,0.0,0
251,AFOF11,Títulos e Val. Mob.,94.00,1005.0,1.00,1.07,3.11,6.25,0.00,1.04,...,6.984347e+07,101.05,0.93,0.99,1.26,2.26,3.24,0.00,0.0,0
149,AIEC11,Lajes Corporativas,83.49,1752.0,0.68,0.88,2.49,4.95,9.01,0.83,...,4.918313e+08,101.93,0.82,0.67,0.03,0.69,1.30,0.00,0.0,2
3,ALMI11,Lajes Corporativas,890.00,15.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.504877e+08,2253.05,0.40,0.00,0.00,0.00,0.00,64.05,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,XPML11,Shoppings,94.64,41437.0,0.64,0.71,2.24,3.93,6.37,0.75,...,1.900952e+09,101.76,0.93,0.59,0.00,0.59,0.59,3.90,0.0,16
103,XPPR11,Outros,56.31,19125.0,0.45,0.77,2.28,4.90,9.36,0.76,...,5.775625e+08,78.94,0.71,0.57,-3.56,-3.01,-2.48,46.00,0.0,4
141,XPSF11,Outros,70.01,19743.0,0.66,0.91,2.58,5.30,10.12,0.86,...,3.702510e+08,85.50,0.82,0.77,-2.97,-2.22,-1.50,0.00,0.0,0
2,XTED11,Lajes Corporativas,6.20,337.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.739193e+07,13.94,0.44,0.00,0.00,0.00,0.00,0.00,100.0,1
64,YUFI11B,Residencial,0.00,0.0,0.84,0.00,0.00,0.00,0.00,0.00,...,4.135436e+07,104.65,0.00,0.80,0.20,1.00,1.52,0.00,0.0,0

In [22]:
data_frame.describe()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,...,2.770000e+02,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000
mean,486.995018,15878.212996,3.601661,0.804693,2.283466,4.027256,6.542347,0.761119,0.671372,0.545162,...,5.177022e+08,528.697726,0.845126,0.714585,-0.288195,0.423285,0.912924,6.631155,1.208339,3.148014
std,4816.875061,45656.844843,41.111742,0.425465,1.265314,2.495814,4.825972,0.421781,0.415943,0.402389,...,7.738358e+08,4628.161947,0.491893,0.485727,1.459705,1.469301,1.602041,16.784331,7.568895,7.744781
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-8.707885e+06,-11.480000,-0.710000,0.000000,-13.830000,-13.480000,-13.480000,0.000000,0.000000,0.000000
25%,65.550000,109.000000,0.480000,0.630000,1.750000,2.730000,0.000000,0.580000,0.460000,0.000000,...,1.032518e+08,87.640000,0.730000,0.470000,-0.200000,0.000000,0.230000,0.000000,0.000000,0.000000
50%,88.500000,2150.000000,0.720000,0.840000,2.340000,4.460000,7.430000,0.780000,0.740000,0.620000,...,2.359198e+08,97.870000,0.870000,0.700000,0.000000,0.550000,0.940000,0.000000,0.000000,0.000000
75%,101.620000,12670.000000,1.100000,1.070000,3.110000,5.570000,9.930000,1.040000,0.930000,0.830000,...,5.775625e+08,109.280000,0.990000,1.050000,0.000000,0.870000,1.390000,2.770000,0.000000,3.000000
max,76000.000000,524297.000000,684.380000,2.950000,6.210000,9.210000,21.800000,2.070000,1.530000,1.820000,...,6.888026e+09,71349.740000,7.600000,3.960000,11.170000,11.190000,11.260000,100.000000,100.000000,72.000000